# Generated by Django 3.1.6 on 2021-02-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=200)),
                ('mobile', models.CharField(default='', max_length=200)),
                ('rent_type', models.CharField(default='', max_length=200)),
                ('room_number', models.CharField(default='', max_length=200)),
                ('client_type', models.CharField(default='', max_length=200)),
                ('more_details', models.CharField(default='', max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.ownerdetail')),
            ],
        ),
    ]
