# Generated by Django 3.1.6 on 2021-03-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20210302_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housedetail',
            old_name='user_id',
            new_name='user',
        ),
    ]
