# Generated by Django 3.1.6 on 2021-03-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20210302_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetail',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
