# Generated by Django 3.1.6 on 2021-03-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20210302_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.housedetail')),
            ],
        ),
    ]
