# Generated by Django 3.1.6 on 2021-03-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedetail',
            name='image',
            field=models.FileField(default='', upload_to='image'),
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
