# Generated by Django 3.1.6 on 2021-03-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_auto_20210308_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetail',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
