# Generated by Django 3.1.6 on 2021-03-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_auto_20210308_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
