# Generated by Django 3.1.6 on 2021-03-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_clientcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedetail',
            name='client_type_a',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='housedetail',
            name='contact_person',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='housedetail',
            name='client_type',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
