# Generated by Django 3.1.6 on 2021-03-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_housedetail_monthly_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetail',
            name='monthly_price',
            field=models.CharField(default='Negotiable', max_length=200),
        ),
    ]
