# Generated by Django 3.1.6 on 2021-04-20 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0012_auto_20210318_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetail',
            name='monthly_price',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='housedetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
