# Generated by Django 3.1.6 on 2021-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_auto_20210420_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetail',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
